### ISSUE TITLE
考虑到国内的开发者大部分是没有kimi的api，我想我们可以转发提供一层，方便大家快速使用起来！

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/kimi-commits-intellij#4]

**Comment by Leizhenpeng** [comment]
初步打算   
1. 功能完善：把kimi 的api的四个url转发 [https://moonshot.feishu.cn/docx/RnkWdeFo8oQabzxYFVwcNg1Mn9g?from=from_copylink](https://moonshot.feishu.cn/docx/RnkWdeFo8oQabzxYFVwcNg1Mn9g?from=from_copylink)  
2. 在我们自定义的hostUrl上  
3. 授权的key逻辑：  
  a. 开发者需要star我们的[仓库](https://github.com/ConnectAI-E/kimi-commits-intellij/)  
  b. star后，开发者的Github 个人链接或者用户名作为key  
4. 防护套刷的措施  
  a. 每日限制合理使用token  
  b. 其他方式额外讨论）

**Comment by xxr3376** [comment]
FYI 近期（预计一周内）kimichat API 将会开放注册

**Comment by Leizhenpeng** [comment]
![image](https://github.com/ConnectAI-E/kimi-commits-intellij/assets/50035229/b395b100-4fda-4cc1-9d7c-3ced26a5c703)

kimi API 已经公测拉~
