### ISSUE TITLE
Temperture=0.3 is recommend for code-related tasks

### ISSUE THREAD

**Issue by xxr3376** [ConnectAI-E/kimi-commits-intellij#5]
https://github.com/ConnectAI-E/kimi-commits-intellij/blob/d2ffcaf3862b8a529c76b44b503af2b82131ac3c/src/main/kotlin/com/github/connectai_e/kimi/commits/intellij/settings/AppSettings.kt#L48

**Comment by Leizhenpeng** [comment]
nice tip

**Comment by Leizhenpeng** [comment]
不过在setting的面版用户是可以自己调整的哈
![image](https://github.com/ConnectAI-E/kimi-commits-intellij/assets/50035229/d1c792be-c2d9-4763-b68b-9d7f9d2fe6df)

**Comment by Leizhenpeng** [comment]
我们可以调整一下默认的setting

**Comment by Leizhenpeng** [comment]
https://github.com/ConnectAI-E/kimi-commits-intellij/pull/7
